version: '3'
services:
  backend1:
    build: .
    image: bac:1.0
    container_name: bac1
    stdin_open: true
    ports:
      - 5001:5000

  backend2:
    image: bac:1.0        
    container_name: bac2
    stdin_open: true
    ports:
      - 5002:5000
